
[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"


[tool.pylint.messages_control]
max-line-length = 88
disable = [
    "fixme",
    "line-too-long",
    "no-else-return",
    "missing-docstring",
]
